### PR TITLE
WIP: Use Velodyne ring data in row estimation

### PR DESCRIPTION
**Pull request by Kallista**
This fix addresses this issue described in the README:

> One important thing to keep in mind is that our current implementation for range image projection is only suitable for sensors that have evenly distributed channels. If you want to use our algorithm with Velodyne VLP-32c or HDL-64e, you need to write your own implementation for such projection. If the point cloud is not projected properly, you will lose many points and performance.

As I understand, the angle_res_y and ang_bottom are used only to assign a row/ring to a point, as in line 198 of imageProjection.cpp:
`rowIdn = (verticalAngle + ang_bottom) / ang_res_y;`
`if (rowIdn < 0 || rowIdn >= N_SCAN)
                continue;`

If linked with the [velodyne_driver](https://github.com/ros-drivers/velodyne) package, it is possible to use the special point type of the driver, where instead of using the angle calculation, the point information provides the ring number. This will only work for supported velodyne lidars of course but automatically gets rid of the "evenly distributed channels" assumption for VLP-32c or HDL-64e and also works for all other sorts of Velodyne LiDARs.

That row now becomes this:
`rowIdn = laserCloudIn->points[i].ring;`

I tested using the provided bag files and it looks ok. My VLP-32c dataset tests work better, but weren't conclusive, since the scenery was too sparse for proper mapping. I will still fix the following:
- [ ] make driver optional in cmake and use point type only when driver is found
- [ ] investigate if only laserCloudIn can use the new point type, as afaik f.e. KdTreeFLANN does not support different point types. If yes, will require two point types in the code. 

but before I get to that, can you please inform me if this is a correct way to do this? Is there anything I missed?

### CODE REVIEW

**Comment by Kallista** [comment]
Also, what is groundScanInd?

**Comment by YoshuaNava** [comment]
Kallista, could you maybe show some screenshots of the data? To visualize the effects of your change.

**Comment by Kallista** [comment]
Sure, I might need some time for that to find the data I evaluated this on though.

BTW, I will probably close this pull request since I learned that optional packages in catkin are not possible. It can stay listed to act as a pointer of the fork I can maintain.

I am going to also soon work on some Hesai LiDARs, and since their driver is a fork of the velodyne driver, I can implement for those lidars the same thing too.

**Comment by facontidavide** [comment]
This seems like an important improvement. 

Reviewing the source code I was also concerned about the assumptions made at  line 198 of imageProjection.cpp.

**Comment by YoshuaNava** [comment]
I agree with @facontidavide.

I have to say that I'm not very convinced of introducing a dependency to the Velodyne ROS packages. SLAM algorithms should remain sensor-agnostic as much as possible. In the future we should find a way to do this in a more generic way.


Apart from that, have you tested the changes?

**Comment by facontidavide** [comment]
I think there could be a potential solution to deal with this:

Looking at [this](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/PointCloud2.html), we may notice that it is possible to double check if the original message has "Ring" in `PointField[] fields`.

If we then define conservatively `PointType` as PointXYZIR (with ring information) we can easily deal with laser data that has or doesn't have the ring information.

But this is of course a change that need to be tested carefully ;)

**Pull request closed without merging**
