### PR TITLE
 Bug fix for Ctrl-C to save map

### PR DESCRIPTION
**Pull request by MikeZhu92**
* Add the missing fileDirectory variable to utility.h #87 
* Fix globalMapKeyFramesDS saving problem:
The `globalMapKeyFramesDS` ptr has been cleared in `publishGlobalMap()` before saving to pcd file. Therefore you will come up with empty pointcloud pcl::io exception.
A new pointer has been added to save the latest globalMapKeyFramesDS pointcloud.

### CODE REVIEW

**Comment by MikeZhu92** [comment]
This is a PR for fixing some minor issues in the latest commit.
I'm trying to fix the code following the original style adding minimum changes.
Feel free to leave comments below.

**Comment by TixiaoShan** [comment]
Hi @MikeZhu92 
Thanks for point this out. Since I edited the file on the Github page, I wasn't able to compile it and caused the bug.

**Comment by MikeZhu92** [comment]
Close this PR since bug has been fixed :)

**Comment by xiaoxueshengyao** [comment]
Hello, thanks for your solution. But I still can not get the finalcloud.pcd with all those fixing.  I can get the other three pcd files. No data in the ptr latestGlobalMapKeyFramesDS. Is it my own error? And when I comment // mtx.lock() and // mtx.unlock() in publishGlobalMap(), then I got the finalcloud.pcd file.

**Comment by MikeZhu92** [comment]
> Hello, thanks for your solution. But I still can not get the finalcloud.pcd with all those fixing. I can get the other three pcd files. No data in the ptr latestGlobalMapKeyFramesDS. Is it my own error? And when I comment // mtx.lock() and // mtx.unlock() in publishGlobalMap(), then I got the finalcloud.pcd file.

There was a major code refactor after this MR and all the commit history were gone. So you might want to check if those changes are still there.

**Pull request closed without merging**
